import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import fixture from './fixtures/join-materialize-native.mjs';
import {hydrate} from './fixtures/output-links-hydrate.mjs';
import {makeWorkspaceUiCode,validateUiAction} from '../lib/workspace-ui.mjs';
import {makeNodeMappingContextCode} from '../lib/node-mapping-context.mjs';
import {configureJoinOutput} from '../lib/join-mappings.mjs';
const {chromium}=createRequire(import.meta.url)('playwright');
const config=JSON.parse(fs.readFileSync(new URL('./fixtures/join-source-fetch-native.json',import.meta.url)));
const captured=fixture['pair-LKey-native-preflight.json'].native;
const prepared=fixture.prepared;
const binding={document_id:prepared.document_id,workflow_ref:prepared.workflow_ref,node:{document_id:prepared.document_id,workflow_id:prepared.workflow_ref.workflow_id,node_id:captured.ledger[0].node_id}};
for(const variant of ['full','partial','custom','foreign_controller','duplicate_ledger','two_null_pairs','missing_inventory','foreign_binding','missing_cell','origin_missing','pending','epoch','retained_foreign_controller','retained_pending','lost_selection','lost_unlink','lost_reconnect','changed_unbound_definition','changed_reconnected_origin','pending_after_unlink','stale_reconnect_ref','stale_unbound_label','stale_unbound_type'])test('Join materializer measured route: '+variant,async()=>{
 const browser=await chromium.launch({executablePath:process.env.LOGINOM_FIXTURE_BROWSER,headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:captured.viewport});await context.route('**/*',r=>r.fulfill({status:200,contentType:'text/html',body:'<html><body></body></html>'}));const page=await context.newPage();
 let state,selectedName,gestures=0,loaded=false;const receipts=[],observations=[];let dispatch=0;for(const key of ['click','down']){const original=page.mouse[key].bind(page.mouse);page.mouse[key]=async(...args)=>{dispatch++;const r=await original(...args);if(variant==='lost_selection'&&dispatch===1||variant==='lost_unlink'&&dispatch===2||variant==='lost_reconnect'&&dispatch===3)throw Error('lost reply after gesture');return r;};}
 const load=async key=>{const d=fixture[key];await hydrate(page,d.native,loaded?'transition':undefined,prepared,d.settlement);loaded=true;await page.evaluate(pressed=>{const e=[...document.querySelectorAll('[data-tid]')].find(e=>e.getAttribute('data-tid').endsWith(';btnAutoSyncThroughColumns'));Ext.getCmp(e.id).pressed=pressed;for(const input of document.querySelectorAll('input.x-form-radio')){const display=input.nextElementSibling;if(display?.tagName==='SPAN'){input.parentElement.append(input,display);}}},d.autosync_receipt.value);};
 const execute=options=>new Function('page',`return (${makeWorkspaceUiCode({expected_build:captured.loginom_build,expected_origin:captured.origin,prepared_node_context:binding,...options})})(page)`)(page);
 const channel={async observe(options={}){let r=await execute({mode:'observe',read_mappings:options.readMappings,output_column_page:options.outputColumnPage});assert.equal(r.status,'SUCCEEDED',JSON.stringify(r.error));r=await execute({mode:'observe',root_ref:r.output.wizard.root_ref,read_mappings:options.readMappings,output_column_page:options.outputColumnPage});assert.equal(r.status,'SUCCEEDED',JSON.stringify(r.error));state=r.output;if(options.readMappings)state.node_mapping=await new Function('page',`return (${makeNodeMappingContextCode(binding)})(page)`)(page);observations.push({condition:options.condition,state:structuredClone(state)});assert.ok(!options.ready||options.ready(state),options.condition+' '+JSON.stringify({mapping:state.node_mapping,columns:state.wizard.output_columns,stage:state.wizard.stage}));return structuredClone(state);},async perform(o){assert(o.ready(state),o.condition);const a=o.resolve(state);o.identity(state);validateUiAction(a,state);if(dispatch===0&&['epoch','retained_foreign_controller','retained_pending'].includes(variant))await page.evaluate(v=>{if(v==='epoch')document.querySelector('[data-tid$=";WizrdMCF"]').setAttribute('data-counterfactual-epoch','1');else if(v==='retained_pending')__nativeFixture.c.FLinksUpdateMode=true;else __nativeFixture.model.FWizardItems.FItems[0].Wizard={};},variant);if(dispatch===2&&['pending_after_unlink','stale_reconnect_ref'].includes(variant))await page.evaluate(v=>{if(v==='pending_after_unlink')__nativeFixture.c.FLinksUpdateMode=true;else document.querySelector('[data-tid$="colDisplayName_LKey"]').setAttribute('data-tid','foreign');},variant);const e=state.ui.elements.find(e=>e.ref===a.ref);const result=await execute({mode:'act',snapshot:state,action:a});receipts.push(result);assert.equal(result.status,'SUCCEEDED',JSON.stringify(result.error));gestures++;
  if(a.verb==='drag'){await load(`pair-${selectedName}-native-settled-reconnected.json`);if(variant==='changed_reconnected_origin')await page.evaluate(()=>{const {get,grids}=__nativeFixture;get(grids[1].records[1].object).data.OriginType=2;});}
  else if(e.date_time_cell?.role==='output_source'){selectedName=e.date_time_cell.link.target.Name;await load(`pair-${selectedName}-native-preflight.json`);}
  else if(e.date_time_cell?.role==='output_relation_remove'){await load(`pair-${selectedName}-native-settled-unbound.json`);if(['stale_unbound_label','stale_unbound_type'].includes(variant))await page.evaluate(v=>{const {get,grids}=__nativeFixture;get(grids[1].records[0].object).data[v==='stale_unbound_label'?'SourceDisplayName':'SourceDataType']=v==='stale_unbound_label'?'foreign':5;},variant);if(variant==='changed_unbound_definition')await page.evaluate(()=>{const {get,grids}=__nativeFixture;get(grids[1].records[1].object).data.OriginType=1;});}
  else if(e.tid.endsWith(';rbTable;DisplayEl'))await load('table-rendered-before-reorder-native.json');
  else if(e.tid.includes(';colName_'))await page.evaluate(tid=>{const {get,grids}=__nativeFixture,cell=[...document.querySelectorAll('[data-tid]')].find(e=>e.getAttribute('data-tid')===tid),row=cell.closest('table.x-grid-item');grids[1].selected=[grids[1].records.find(r=>String(r.internalId)===row.getAttribute('data-recordid')).object];for(const x of row.parentElement.querySelectorAll('table.x-grid-item'))x.classList.toggle('x-grid-item-selected',x===row);},e.tid);
  else if(e.tid.endsWith(';btnMoveMappingColumnUp'))await page.evaluate(()=>{const {get,grids}=__nativeFixture,g=grids[1],store=get(g.store),items=store.getData().items,selected=get(g.selected[0]),index=items.indexOf(selected);if(index<1)throw Error('invalid inert move');[items[index-1],items[index]]=[items[index],items[index-1]];items.forEach((r,i)=>r.data.Index=i);const view=get(g.element??g.view)?.el?.dom??document.querySelector('[data-tid$="grdTargetColumns;tbl"]'),rows=[...view.querySelectorAll('table.x-grid-item')],positions=rows.map(e=>e.getBoundingClientRect().y).sort((a,b)=>a-b);for(const [i,r] of items.entries()){const row=rows.find(e=>e.getAttribute('data-recordid')===String(r.internalId));const dy=positions[i]-row.getBoundingClientRect().y;for(const e of [row,...row.querySelectorAll('*')]){const b=e.getBoundingClientRect();e.style.top=(b.y+dy)+'px';e.getBoundingClientRect=()=>({...b,y:b.y+dy,top:b.y+dy,bottom:b.y+dy+b.height});}row.setAttribute('data-recordindex',String(i));row.parentElement.append(row);}},undefined);
  else throw Error('unhandled inert fixture gesture '+e.tid);
  return result;
 }};
 try{await load(variant==='partial'?'pair-LValue-native-preflight.json':variant==='custom'?'pair-RValue-native-settled-reconnected.json':'pair-LKey-native-preflight.json');
  await page.evaluate(v=>{const {get,grids,model,c}=__nativeFixture;
   if(v==='foreign_controller')model.FWizardItems.FItems[0].Wizard={};
   if(v==='duplicate_ledger'){const p=__loginomDockPreparationV1,r=[...p.outputPortOpenReceipts.values()][0];p.outputPortOpenReceipts.set('foreign',{...r,key:'foreign',operation_id:'foreign'});}
   if(v==='two_null_pairs')for(const i of [0,1]){const t=get(grids[1].records[i].object),s=t.data.ConnectedRecord;t.data.ConnectedRecord=null;s.data.ConnectedRecord=null;}
   if(v==='missing_inventory')get(grids[0].store).getTotalCount=()=>5;
   if(v==='foreign_binding')get(grids[1].records[0].object).data.ConnectedRecord={data:{}};
   if(v==='missing_cell')document.querySelector('[data-tid$="colSourceName_LKey"]').remove();
   if(v==='origin_missing')delete get(grids[1].records[1].object).data.OriginType;
   if(v==='pending')c.FLinksUpdateMode=true;
  },variant);
  const invoke=async()=>{state=await channel.observe({readMappings:true});return configureJoinOutput(channel,{...config.configuration,node_context:state.node_mapping.node_context,default_output_order:true},config.parameters,{});};
  if(['full','partial','custom'].includes(variant)){const result=await invoke();assert.equal(result.verified,true);assert.equal(result.changes[0].materialized_fields.length,variant==='full'?6:variant==='partial'?4:0);assert.equal(result.changes[0].persisted_content_verified,false);assert.deepEqual(result.native_mapping.target_fields.map(f=>f.name),config.configuration.input_fields.flat().map(f=>f.name));assert.equal(receipts.length,gestures);
   const final=await channel.observe({outputColumnPage:{offset:0,limit:8}}),es=final.ui.elements.filter(e=>e.wizard_finish?.mode==='output_port'&&e.allowed_actions.includes('finish_wizard'));assert.equal(es.length,1);validateUiAction({verb:'finish_wizard',ref:es[0].ref},final);
  }else{await assert.rejects(invoke());const expected=variant==='lost_selection'?1:variant==='lost_unlink'||variant==='changed_unbound_definition'||variant==='pending_after_unlink'||variant==='stale_reconnect_ref'||variant==='stale_unbound_label'||variant==='stale_unbound_type'?2:variant==='lost_reconnect'||variant==='changed_reconnected_origin'?3:0;assert.equal(dispatch,expected);assert.ok(receipts.every(r=>!r.trace?.some(t=>['finish_wizard','execute'].includes(t.verb))));if(variant.startsWith('lost_')){assert.equal(receipts.at(-1).status,'AMBIGUOUS');assert.equal(receipts.at(-1).effect_possible,true);}if(expected>=2)assert.ok(receipts.some(r=>r.effect_possible===true),'prior effects must remain possible');if(variant.startsWith('retained_')||variant==='epoch'){assert.equal(receipts.at(-1).status,'NOT_APPLIED');assert.equal(receipts.at(-1).effect_possible,false);}}
 }finally{await context.close();await browser.close();if(process.env.LOGINOM_MATERIALIZER_EVIDENCE){fs.mkdirSync(process.env.LOGINOM_MATERIALIZER_EVIDENCE,{recursive:true});fs.writeFileSync(process.env.LOGINOM_MATERIALIZER_EVIDENCE+'/'+variant+'.json',JSON.stringify({variant,dispatch,gestures,receipts,observations,browser_closed:true},null,2)+'\n');}}
});
