import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {runReplacementDiagnostic} from '../replacement-live-owner.mjs';
import {makePackageCleanupCode} from '../../../packages/loginom-runtime/client/lib/package-cleanup.mjs';
const identity={sessionId:'session',account:'own',packagePath:'/own/new.lgp',loginomUrl:'https://example.com/app/',loginomBuild:'7.4.2'};
const prepared={status:'READY',document_id:'original-document',package_ref:{path:identity.packagePath},workflow_ref:{tab_tid:'original-tab'}};
async function fixture(fn){const directory=await mkdtemp(join(tmpdir(),'replacement-owner-')),events=[],page={marker:'original'},state={pending:false,refuse:false,closed:false,calls:0};const context={close:async()=>{state.closed=true;events.push('browser exit');}};const execute=async()=>{state.calls++;if(state.refuse)return {status:'BLOCKED'};events.push('close/logout');return {status:'SUCCEEDED',package_closed:true,logged_out:true,session_id:identity.sessionId,document_id:prepared.document_id,account:identity.account,package_path:identity.packagePath};};const options={directory,page,context,execute,identity,makeCleanupCode:makePackageCleanupCode,runtime:{hasUnsettledWork:()=>state.pending}};try{await fn({options,state,events,page,context,execute});}finally{await rm(directory,{recursive:true,force:true});}}
for(const rejection of [Error('original'),undefined,null,false,0,''])test('preserve original rejection '+String(rejection),()=>fixture(async({options,state,page,context,execute})=>{
 const owner=await runReplacementDiagnostic(options,{},async({bindPrepared})=>{await bindPrepared(prepared);throw rejection;});assert.equal(owner.error,rejection);assert.equal(owner.failed,true);assert.equal(owner.page,page);assert.equal(owner.context,context);assert.equal(owner.execute,execute);assert.equal(state.closed,false);assert.equal(state.calls,0);assert.equal(await owner.page.marker,'original');await owner.recover();assert.equal(state.closed,true);
}));
test('success durable cleanup before browser exit',()=>fixture(async({options,state,events})=>{const owner=await runReplacementDiagnostic(options,{},async({bindPrepared})=>{await bindPrepared(prepared);return 'done';});assert.equal(owner.closed,true);assert.equal(owner.value,'done');assert.deepEqual(events,['close/logout','browser exit']);assert.equal(JSON.parse(await readFile(join(options.directory,'cleanup.json'))).confirmed,true);}));
test('cleanup refusal retains page and recovery does not replay scenario',()=>fixture(async({options,state,page})=>{state.refuse=true;let attempts=0;const owner=await runReplacementDiagnostic(options,{},async({bindPrepared})=>{attempts++;await bindPrepared(prepared);});assert.equal(owner.failed,true);assert.equal(owner.page,page);assert.equal(state.closed,false);state.refuse=false;await owner.recover();assert.equal(attempts,1);assert.equal(state.closed,true);}));
test('pending forbids recovery and retains source page',()=>fixture(async({options,state})=>{const owner=await runReplacementDiagnostic(options,{},async({bindPrepared})=>{await bindPrepared(prepared);state.pending=true;throw Error('ambiguous');});await assert.rejects(owner.recover(),/PENDING_OPERATION_PRESERVED/);assert.equal(state.calls,0);assert.equal(state.closed,false);}));
test('foreign package binding cannot close transport',()=>fixture(async({options,state})=>{const owner=await runReplacementDiagnostic(options,{},async({bindPrepared})=>bindPrepared({...prepared,package_ref:{path:'/foreign/x.lgp'}}));assert.equal(owner.failed,true);assert.equal(state.calls,0);assert.equal(state.closed,false);await assert.rejects(owner.recover(),/IDENTITY_UNCONFIRMED/);}));
