import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["LOGINOM_AI_AGENT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["LOGINOM_AI_AGENT_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("LOGINOM_AI_AGENT_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  LOGINOM_AI_AGENT_AUTO_HEAP_SNAPSHOT: truthy("LOGINOM_AI_AGENT_AUTO_HEAP_SNAPSHOT"),
  LOGINOM_AI_AGENT_GIT_BASH_PATH: process.env["LOGINOM_AI_AGENT_GIT_BASH_PATH"],
  LOGINOM_AI_AGENT_CONFIG: process.env["LOGINOM_AI_AGENT_CONFIG"],
  LOGINOM_AI_AGENT_CONFIG_CONTENT: process.env["LOGINOM_AI_AGENT_CONFIG_CONTENT"],
  LOGINOM_AI_AGENT_DISABLE_AUTOUPDATE: truthy("LOGINOM_AI_AGENT_DISABLE_AUTOUPDATE"),
  LOGINOM_AI_AGENT_ALWAYS_NOTIFY_UPDATE: truthy("LOGINOM_AI_AGENT_ALWAYS_NOTIFY_UPDATE"),
  LOGINOM_AI_AGENT_DISABLE_PRUNE: truthy("LOGINOM_AI_AGENT_DISABLE_PRUNE"),
  LOGINOM_AI_AGENT_DISABLE_TERMINAL_TITLE: truthy("LOGINOM_AI_AGENT_DISABLE_TERMINAL_TITLE"),
  LOGINOM_AI_AGENT_SHOW_TTFD: truthy("LOGINOM_AI_AGENT_SHOW_TTFD"),
  LOGINOM_AI_AGENT_DISABLE_AUTOCOMPACT: truthy("LOGINOM_AI_AGENT_DISABLE_AUTOCOMPACT"),
  LOGINOM_AI_AGENT_DISABLE_MODELS_FETCH: truthy("LOGINOM_AI_AGENT_DISABLE_MODELS_FETCH"),
  LOGINOM_AI_AGENT_DISABLE_MOUSE: truthy("LOGINOM_AI_AGENT_DISABLE_MOUSE"),
  LOGINOM_AI_AGENT_FAKE_VCS: process.env["LOGINOM_AI_AGENT_FAKE_VCS"],
  LOGINOM_AI_AGENT_SERVER_PASSWORD: process.env["LOGINOM_AI_AGENT_SERVER_PASSWORD"],
  LOGINOM_AI_AGENT_SERVER_USERNAME: process.env["LOGINOM_AI_AGENT_SERVER_USERNAME"],
  LOGINOM_AI_AGENT_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("LOGINOM_AI_AGENT_DISABLE_FFF"),

  // Experimental
  LOGINOM_AI_AGENT_EXPERIMENTAL_FILEWATCHER: Config.boolean("LOGINOM_AI_AGENT_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  LOGINOM_AI_AGENT_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("LOGINOM_AI_AGENT_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  LOGINOM_AI_AGENT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("LOGINOM_AI_AGENT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  LOGINOM_AI_AGENT_MODELS_URL: process.env["LOGINOM_AI_AGENT_MODELS_URL"],
  LOGINOM_AI_AGENT_MODELS_PATH: process.env["LOGINOM_AI_AGENT_MODELS_PATH"],
  LOGINOM_AI_AGENT_DB: process.env["LOGINOM_AI_AGENT_DB"],

  LOGINOM_AI_AGENT_WORKSPACE_ID: process.env["LOGINOM_AI_AGENT_WORKSPACE_ID"],
  LOGINOM_AI_AGENT_EXPERIMENTAL_WORKSPACES: enabledByExperimental("LOGINOM_AI_AGENT_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get LOGINOM_AI_AGENT_DISABLE_PROJECT_CONFIG() {
    return truthy("LOGINOM_AI_AGENT_DISABLE_PROJECT_CONFIG")
  },
  get LOGINOM_AI_AGENT_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("LOGINOM_AI_AGENT_EXPERIMENTAL_REFERENCES")
  },
  get LOGINOM_AI_AGENT_TUI_CONFIG() {
    return process.env["LOGINOM_AI_AGENT_TUI_CONFIG"]
  },
  get LOGINOM_AI_AGENT_CONFIG_DIR() {
    return process.env["LOGINOM_AI_AGENT_CONFIG_DIR"]
  },
  get LOGINOM_AI_AGENT_PURE() {
    return truthy("LOGINOM_AI_AGENT_PURE")
  },
  get LOGINOM_AI_AGENT_PERMISSION() {
    return process.env["LOGINOM_AI_AGENT_PERMISSION"]
  },
  get LOGINOM_AI_AGENT_PLUGIN_META_FILE() {
    return process.env["LOGINOM_AI_AGENT_PLUGIN_META_FILE"]
  },
  get LOGINOM_AI_AGENT_CLIENT() {
    return process.env["LOGINOM_AI_AGENT_CLIENT"] ?? "cli"
  },
}
